path:
  - value: |
      {{ .Home }}/.local/bin
    if: eq .OS "linux"
  - value: |
      {{ .Home }}\AppData\Local\mise\shims
    if: and (eq .OS "windows") (hasCommand "mise")
alias:
  - name: n
    value: nvim
    if: hasCommand "nvim"
  - name: lg
    value: lazygit
    if: hasCommand "lazygit"
  - name: ld
    value: lazydocker
    if: hasCommand "lazydocker"
  - name: pd
    value: podman
    if: hasCommand "podman"
  - name: which
    value: Get-Command
    if: match .Shell "pwsh"
  - name: open
    value: Invoke-Item
    if: match .Shell "pwsh"
  - name: o
    value: ollama
    if: hasCommand "ollama"
  - name: w
    value: wormhole
    if: hasCommand "wormhole"
  - name: zj
    value: zellij
    if: hasCommand "zellij"
  - name: tm
    value: tmux
    if: hasCommand "tmux"
  - name: zj
    value: zellij
    if: hasCommand "zellij"
  - name: btop
    value: btop4win
    if: hasCommand "btop4win"
  - name: st
    value: status
    type: git
  - name: logp
    value: log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative
    type: git
  - name: cat
    value: bat
    if: hasCommand "bat"
  - name: e
    value: eza
    if: hasCommand "eza"
env:
  - name: EZA_ICONS_AUTO
    value: "always"
  - name: CARAPACE_BRIDGES
    value: "zsh,fish,bash,inshellisense"
  - name: MANPAGER
    value: "nvim +Man!"
    if: eq .OS "linux"
  - name: EDITOR
    value: "nvim"
  - name: BAT_THEME
    value: "base16"
  - name: BAT_PAGER
    value: "less -RF"
  - name: FZF_DEFAULT_OPTS
    value: "--height 50% --layout=reverse"
  - name: FZF_COMPLETION_TRIGGER
    value: "**"
  - name: VIRTUAL_ENV_DISABLE_PROMPT
    value: 1
  - name: CUSTOMPSHOME
    value: '{{ .Home }}\.config\powershell'
    if: eq .OS "windows"
  - name: NVIM_THEME
    value: "catppuccin-nvim"
  - name: NEOVIDE_OPENGL
    value: 1
    persist: true
    if: eq .OS "windows"
  - name: PIP_REQUIRE_VIRTUALENV
    value: "true"
script:
  # Nushell
  - value: |
      $env.config.edit_mode = "vi"
      $env.config.cursor_shape = {
        vi_insert: line,
        vi_normal: block,
      }
    if: match .Shell "nu"
  - value: |
      source ~/.zoxide.nu
    if: and (match .Shell "nu") (hasCommand "zoxide")
  - value: |
      source $"($nu.cache-dir)/carapace.nu"
    if: and (match .Shell "nu") (hasCommand "carapace")

  # Zsh
  - value: |
      eval "$(starship init zsh)"
    if: and (match .Shell "zsh") (hasCommand "starship")
  - value: |
      # ${UserConfigDir}/zsh/.zshrc
      zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
      source <(carapace _carapace)
    if: and (match .Shell "zsh") (hasCommand "carapace")

  # Powershell
  - value: |
      . "$env:CUSTOMPSHOME\PSReadline.ps1"
    if: match .Shell "pwsh"
  - value: |
      function Invoke-Starship-PreCommand {
        $host.ui.RawUI.WindowTitle = "$env:USERNAME@$env:COMPUTERNAME`: $pwd `a"

        $loc = $executionContext.SessionState.Path.CurrentLocation;
        $prompt = "$([char]27)]9;12$([char]7)"

        if ($loc.Provider.Name -eq "FileSystem")
        {
          $prompt += "$([char]27)]9;9;`"$($loc.ProviderPath)`"$([char]27)\"
        }

        $host.ui.Write($prompt)
      }

      Invoke-Expression (&starship init powershell)
    if: and (match .Shell "pwsh") (hasCommand "starship")
  - value: |
      (&mise activate pwsh) | Out-String | Invoke-Expression
    if: and (match .Shell "pwsh") (hasCommand "mise")
  - value: |
      Invoke-Expression (& { (zoxide init powershell | Out-String) })
    if: and (match .Shell "pwsh") (hasCommand "zoxide")
  - value: |
      Set-PSReadLineOption -Colors @{ "Selection" = "`e[7m" }
      Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
      carapace _carapace | Out-String | Invoke-Expression
    if: and (match .Shell "pwsh") (hasCommand "carapace")
