path:
  - value: |
      {{ .Home }}/.local/bin
alias:
  - name: n
    value: nvim
    if: hasCommand "nvim"
  - name: lg
    value: lazygit
    if: hasCommand "lazygit"
  - name: ld
    value: lazydocker
    if: hasCommand "lazydocker"
  - name: pd
    value: podman
    if: hasCommand "podman"
  - name: which
    value: Get-Command
    if: match .Shell "pwsh"
  - name: open
    value: Invoke-Item
    if: match .Shell "pwsh"
  - name: o
    value: ollama
    if: hasCommand "ollama"
  - name: w
    value: wormhole
    if: hasCommand "wormhole"
  - name: zj
    value: zellij
    if: hasCommand "zellij"
  - name: tm
    value: tmux
    if: hasCommand "tmux"
  - name: zj
    value: zellij
    if: hasCommand "zellij"
  - name: btop
    value: btop4win
    if: hasCommand "btop4win"
  - name: st
    value: status
    type: git
  - name: logp
    value: log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset" --abbrev-commit --date=relative
    type: git
env:
  - name: MANPAGER
    value: "nvim +Man!"
  - name: EDITOR
    value: "nvim"
  - name: BAT_THEME
    value: "base16"
  - name: BAT_PAGER
    value: "less -RF"
  - name: FZF_DEFAULT_OPTS
    value: "--height 50% --layout=reverse"
  - name: FZF_COMPLETION_TRIGGER
    value: "**"
  - name: VIRTUAL_ENV_DISABLE_PROMPT
    value: 1
  - name: CUSTOMPSHOME
    value: '{{ .Home }}\.config\powershell'
    if: eq .OS "windows"
  - name: NVIM_BACKGROUND
    value: "light"
  - name: NVIM_THEME
    value: "catppuccin"
    persist: true
  - name: NEOVIDE_OPENGL
    value: 1
    persist: true
    if: eq .OS "windows"
  - name: PIP_REQUIRE_VIRTUALENV
    value: "true"
  - name: TYPST_PREVIEW
    value: "http://127.0.0.1:23635"
script:
  - value: |
      command -v bat >/dev/null && alias cat="bat -p"
      if [ $(command -v eza) ]; then
        alias la="eza -aF --group-directories-first --icons"
      fi
    if: match .Shell "zsh"
  - value: |
      # starship
      eval "$(starship init zsh)"

      # ${UserConfigDir}/zsh/.zshrc
      export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
      zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
      source <(carapace _carapace)
    if: match .Shell "zsh"
  - value: |
      if (Get-Command starship -ErrorAction SilentlyContinue) {
        function Invoke-Starship-PreCommand {
          $host.ui.RawUI.WindowTitle = "$env:USERNAME@$env:COMPUTERNAME`: $pwd `a"

          $loc = $executionContext.SessionState.Path.CurrentLocation;
          $prompt = "$([char]27)]9;12$([char]7)"
          
          if ($loc.Provider.Name -eq "FileSystem")
          {
            $prompt += "$([char]27)]9;9;`"$($loc.ProviderPath)`"$([char]27)\"
          }

          $host.ui.Write($prompt)
        }

        Invoke-Expression (&starship init powershell)
      }      
    if: match .Shell "pwsh"
  - value: |
      foreach ($PFunction in Get-ChildItem "$env:CUSTOMPSHOME\functions") {
        if ($PFunction.name -like "*.ps1") {
          . $PFunction
        }
      }

      # conf
      foreach ($PConfig in Get-ChildItem "$env:CUSTOMPSHOME\conf") {
        if ($PConfig.name -like "*.ps1") {
          . $PConfig
        }
      }
    if: match .Shell "pwsh"
  - value: |
      if ( -not ( Get-Command carapace -ErrorAction SilentlyContinue ) ) {
          return
      }

      $env:CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense' # optional
      Set-PSReadLineOption -Colors @{ "Selection" = "`e[7m" }
      Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
      carapace _carapace | Out-String | Invoke-Expression
    if: match .Shell "pwsh"

    # Aliases that require arguments
  - value: |
      function __TOUCH { param([Parameter(ValueFromRemainingArguments=$true)]$args) Get-ChildItem -Path $args | Format-Wide -AutoSize }
      function __CUSTOM_BAT { param( $path ) if (Get-Command bat -ErrorAction SilentlyContinue) { bat -p $path } else { cat $path } }
      function __TOUCH { param([Parameter(ValueFromRemainingArguments=$true)]$args) & New-Item -ItemType File -Path $args }
      function __EXALS { param([Parameter(ValueFromRemainingArguments=$true)]$args) & eza -F --icons --group-directories-first $args }
      function __EXALA { param([Parameter(ValueFromRemainingArguments=$true)]$args) & eza -A -F --icons --group-directories-first $args }
      function __NE { param([Parameter(ValueFromRemainingArguments=$true)]$args) & neovide --grid=120x35 $args }
      function __IMGCAT { param([Parameter(ValueFromRemainingArguments=$true)]$args) & chafa -f sixels $args }

      if (Get-Command eza -ErrorAction SilentlyContinue) {
        Set-Alias -Name la -Value __EXALA
      }
      Set-Alias -Name cat -Value __CUSTOM_BAT
      Set-Alias -Name touch -Value __TOUCH
      Set-Alias -Name ne -Value __NE
      Set-Alias -Name icat -Value __IMGCAT
    if: match .Shell "pwsh"
