theme = "mellow"

[editor]
scrolloff = 10
cursorline = true
line-number = "relative"
color-modes = true
bufferline = "multiple"
idle-timeout = 150
# force true color
true-color = true
rulers = [80, 120]
popup-border = "all"
end-of-line-diagnostics = "warning"

[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spacer", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = [
  "spinner",
  "spacer",
  "diagnostics",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "position-percentage",
  "position",
]

[editor.whitespace.render]
tab = "all"
newline = "all"
space = "all"

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }

[keys.normal.space.q]
q = ":quit-all"
w = ":write-quit-all"
