vim.o.guifont = "Cascadia Code,MonaspiceNe Nerd Font Propo:h12"
vim.g.neovide_opacity = 0.9
vim.g.neovide_show_border = true
vim.g.neovide_window_blurred = true
vim.g.neovide_remember_window_size = true
vim.g.neovide_hide_mouse_when_typing = true
vim.g.neovide_cursor_vfx_mode = "torpedo"
vim.g.neovide_title_background_color =
  string.format("%x", vim.api.nvim_get_hl(0, { id = vim.api.nvim_get_hl_id_by_name("Normal") }).bg)
vim.g.neovide_title_text_color = "#FF69B4"
